# Read data
source("set_up.R")
source("read_data.R")

# User submitted model that predicts risk scores for the second (unlabeled) data
source("example_survival.R")

# Evaluation: score the solution generated by the user
source("evaluation.R")

