# Read data
source("set_up.R")
source("read_data.R")

# User submitted model that predicts risk scores for the second (unlabeled) data
source("example_survival.R")

# Evaluation: score the solution generated by the user
source("evaluation.R")


# This document contains the HF dream challenge modelling
# Modelling with siamcat-lasso regression 
set.seed(5497659)

# load the data
PARAM <- list()
PARAM$folder.R <- paste0(getwd(), "/")
PARAM$folder.testdata <- paste0(PARAM$folder.R, "data/test/")
PARAM$folder.traindata <- paste0(PARAM$folder.R, "data/train/")

# metadata
meta.train <- S1

# choose only HF cases and eliminate "NA"
meta.train <- meta.train %>%
  filter(Event!="NA")
table(meta.train$Event)
dim(meta.train)

# read files for training data
feat.train <- O1
# remove unmapped
toremove = c("ssRNA_positive-strand_viruses", "1", "0")
feat.train <- feat.train[!rownames(feat.train) %in% toremove, ]
rows=rownames(feat.train)
# Convert all variable types to numeric
feat.train <- as.data.frame(apply(feat.train, 2, as.numeric))  
rownames(feat.train) <- rows

# choose sample data
data.sample.tmp <- feat.train[match(rownames(meta.train), colnames(feat.train))]
dim(data.sample.tmp)
# relative abundance
feat.train.rel <- prop.table(as.matrix(data.sample.tmp), 2)
feat.train.rel <- feat.train.rel[rowSums(feat.train.rel >= 10^-5) >= 2, ]
dim(feat.train.rel)

# modelling
source("siamcat.R")
# choose variables for testing confounder
metatest <- c("Age","BMI", "Smoking", "BPtreatment" )
# run modelling
siamcat.main <- runsiamcat(feat.train.rel, meta.train, "siamcat", "1", "lasso", "log.clr", "0.03")


# apply model to test set
# prepare test files
meta.test <- S2 
dim(meta.test)

# read files for testing data
feat.test <- O2
# remove unmapped and weird once
feat.test <- feat.test[!rownames(feat.test) %in% toremove, ]
rows=rownames(feat.test)
# Convert all variable types to numeric
feat.test <- as.data.frame(apply(feat.test, 2, as.numeric))  
rownames(feat.test) <- rows

# choose sample data
data.sample.tmp <- feat.test[match(colnames(feat.test),rownames(meta.test))]
# relative abundance norm
feat.test.rel <- prop.table(as.matrix(data.sample.tmp), 2)
dim(feat.test.rel)

# get predictions based on training data
# create holdout siamcat object
siamcat.holdout <- siamcat(feat=feat.test.rel, 
                           meta=meta.test,
                           verbose=0) 
# make predictions
siamcat.holdout <- make.predictions(siamcat=siamcat.main, 
                                    siamcat.holdout = siamcat.holdout)
pred <- rowMeans(pred_matrix(siamcat.holdout))
# export predictions per study
scores <- data.frame(SampleID=rownames(siamcat.holdout@pred_matrix),
                     Score=pred)
rownames(scores) <- NULL
# save predictions
write.table(scores, paste0('data/test/scores.csv'), sep="\t")

